
import "./globals.css";

import { Suspense } from "react";

export const metadata = {
  title: "Cavernas AND Dragões",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      </head>
      <body>
        <Suspense>
        {children}
        </Suspense>
      </body>
    </html>
  );
}
